#############################################
#   D R O P S   local makefile              #
#############################################

# variables:

DIR = misc

EXEC =

DELETE = $(EXEC)

CPP = $(wildcard *.cpp)

OBJ = $(CPP:%.cpp=%.o)


# rules

default: ClrScr


# include common rules:
include ../Make.common
