VS_BASE_DIR= metis parmetis drops ddd
VS_SUBDIRS= ReleaseSerial Release x64 Debug DebugSerial

VS_DIRS= ReleaseSerial Release x64 DebugSerial Debug \
         metis/ReleaseSerial metis/Release metis/x64 metis/DebugSerial metis/Debug \
         parmetis/ReleaseSerial parmetis/Release parmetis/x64 parmetis/DebugSerial parmetis/Debug \
         ddd/ReleaseSerial ddd/Release ddd/x64 ddd/DebugSerial ddd/Debug \
         Zoltan/ReleaseSerial Zoltan/Release Zoltan/x64 Zoltan/Debug Zoltan/DebugSerial \
         drops/ReleaseSerial drops/Release drops/x64 drops/DebugSerial drops/Debug


distclean:
	/bin/rm -rf $(VS_DIRS) DropsPackage.suo
