#############################################
#   D R O P S   local makefile              #
#############################################

# variables:

DROPS_ROOT=../..

DIR = poisson/pydrops

EXEC =

DELETE = $(EXEC)

CPP = $(wildcard *.cpp)

OBJ = $(CPP:%.cpp=%.o)


# rules

default: ClrScr

# include common rules:
include $(DROPS_ROOT)/Make.common
